<?php

########################################################################
# Extension Manager/Repository config file for ext: "cicregister"
#
# Auto generated by Extension Builder 2011-12-13
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CIC User Registration',
	'description' => 'CIC User Registration is a flexible, extensible, extension for the creation of front-end user accounts that is built on top of ExtBase anf Fluid',
	'category' => 'plugin',
	'author' => 'Zachary Davis',
	'author_email' => 'zach@castironcoding.com',
	'author_company' => 'Cast Iron Coding, Inc',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'cicbase' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>